export const projects = [
  {
    "id": "galaxy",
    "no": "01",
    "name": "GALAXY",
    "category": "INTERACTIVE SCIENCE",
    "tagline": "A real-time 3D solar-system explorer.",
    "stack": "TYPESCRIPT · THREE.JS · EPHEMERIDES · PLAYWRIGHT",
    "status": "LIVE / STABILIZING",
    "accent": "#5EA8FF",
    "accent2": "#8FE0FF",
    "motif": "orbit",
    "live": "https://galaxy.adrianguichard.dev/",
    "secondary": "SOURCE",
    "secondaryUrl": "https://github.com/Addey34/galaxy-3d"
  },
  {
    "id": "ludora",
    "no": "02",
    "name": "LUDORA",
    "category": "BROWSER GAMING",
    "tagline": "A connected library of instant-play games.",
    "stack": "TYPESCRIPT · NAKAMA · REALTIME · PWA",
    "status": "LIVE / ACTIVE DEVELOPMENT",
    "accent": "#4DD8D0",
    "accent2": "#818CF8",
    "motif": "grid",
    "live": "https://ludora.adrianguichard.dev/",
    "secondary": "SHOWCASE",
    "secondaryUrl": "https://github.com/Addey34/ludora-showcase"
  },
  {
    "id": "magnotes",
    "no": "03",
    "name": "MAGNOTES",
    "category": "KNOWLEDGE WORKSPACE",
    "tagline": "A visual workspace for connected thought.",
    "stack": "REACT · TYPESCRIPT · NODE · MONGODB",
    "status": "LIVE / ACTIVE DEVELOPMENT",
    "accent": "#A78BFA",
    "accent2": "#D8B4FE",
    "motif": "graph",
    "live": "https://magnotes.adrianguichard.dev/",
    "secondary": "SOURCE",
    "secondaryUrl": "https://github.com/Addey34/magnotes-frontend"
  },
  {
    "id": "siteguardian",
    "no": "04",
    "name": "SITEGUARDIAN",
    "category": "WEB RELIABILITY",
    "tagline": "Detect website failures before clients do.",
    "stack": "TYPESCRIPT · POSTGRESQL · STRIPE · CI",
    "status": "LIVE / PILOT",
    "accent": "#46D39A",
    "accent2": "#86EFAC",
    "motif": "pulse",
    "live": "https://siteguardian.adrianguichard.dev/",
    "secondary": "PRIVATE SOURCE",
    "secondaryUrl": ""
  },
  {
    "id": "image-generator",
    "no": "05",
    "name": "IMAGE GENERATOR",
    "category": "GENERATIVE AI",
    "tagline": "Local-first generation for image, video and audio.",
    "stack": "PYTHON · FASTAPI · PYTORCH · DIFFUSERS",
    "status": "ACTIVE DEVELOPMENT / PRIVATE SOURCE",
    "accent": "#F28BC3",
    "accent2": "#C084FC",
    "motif": "diffusion",
    "live": "",
    "secondary": "PRIVATE SOURCE",
    "secondaryUrl": ""
  },
  {
    "id": "devisflow",
    "no": "06",
    "name": "DEVISFLOW",
    "category": "BUSINESS WORKFLOW",
    "tagline": "Quotes and follow-up without friction.",
    "stack": "TYPESCRIPT · VITE · DOMAIN MODULES",
    "status": "LIVE / MVP",
    "accent": "#5BC7FF",
    "accent2": "#93C5FD",
    "motif": "flow",
    "live": "https://devisflow.adrianguichard.dev/",
    "secondary": "PRIVATE SOURCE",
    "secondaryUrl": ""
  }
];
